# Generated by Django 6.1.1 on 2026-09-07 23:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha del Cierre')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora Exacta')),
                ('valor_total_bodega', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total ($)')),
                ('operario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operario Responsable')),
            ],
            options={
                'verbose_name': 'Cierre de Inventario',
                'verbose_name_plural': 'Cierres de Inventarios',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='insumo',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Costo por unidad de medida', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario ($)'),
        ),
        migrations.CreateModel(
            name='DetalleInventarioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo_snapshot', models.CharField(max_length=200, verbose_name='Nombre al momento del cierre')),
                ('stock_registrado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Registrado')),
                ('unidad_medida_snapshot', models.CharField(max_length=20, verbose_name='Unidad de Medida')),
                ('precio_unitario_snapshot', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario ($)')),
                ('valor_total_snapshot', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total ($)')),
                ('insumo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_historicos', to='inventario.insumo')),
                ('inventario_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.inventariodiario')),
            ],
            options={
                'verbose_name': 'Detalle de Cierre',
                'verbose_name_plural': 'Detalles de Cierres',
            },
        ),
    ]
