# Generated by Django 6.1.1 on 2026-09-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_inventariodiario_insumo_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarcar para deshabilitar el insumo en lugar de borrarlo.', verbose_name='Habilitado'),
        ),
    ]
